on: push
name: Example Workflow
jobs:
  runNpmEslint:
    name: Run NPM eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run NPM eslint
      uses: anna-money/github-actions-npm@v1
  runDepCheck:
    name : Dependancy check
    steps:
      - uses: actions/checkout@v2
      - name: npm-depcheck
        uses: tj-actions/depcheck@v3
        with:
          dir: '.'
          ignores: 'eslint,babel-*'  